# Generated by Django 3.1.6 on 2021-03-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210319_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='chead2',
        ),
    ]
