# Generated by Django 3.1.6 on 2021-03-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_chead2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='chead2',
            new_name='chead02',
        ),
    ]
